# Generated by Django 4.1 on 2022-09-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_generos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_profissao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('sit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sit_situacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Necessitado',
            fields=[
                ('nec_id', models.AutoField(primary_key=True, serialize=False)),
                ('nec_nome', models.CharField(max_length=100)),
                ('nec_idade', models.IntegerField(default=0)),
                ('nec_logradouro', models.CharField(max_length=100)),
                ('nec_cpf', models.CharField(max_length=14)),
                ('nec_gen_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.genero')),
                ('nec_pro_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.profissao')),
                ('nec_sit_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.situacao')),
            ],
        ),
    ]
