# Generated by Django 4.1 on 2022-10-18 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cid_id', models.AutoField(primary_key=True, serialize=False)),
                ('cid_cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_generos', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Gênero',
            },
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('ong_id', models.AutoField(primary_key=True, serialize=False)),
                ('ong_nome', models.CharField(max_length=100)),
                ('ong_site', models.CharField(max_length=70)),
                ('ong_logradouro', models.CharField(max_length=50)),
                ('ong_cid_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.cidade')),
            ],
            options={
                'verbose_name': 'ONG',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_profissao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('sit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sit_situacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Necessitado',
            fields=[
                ('nec_id', models.AutoField(primary_key=True, serialize=False)),
                ('nec_nome', models.CharField(max_length=100)),
                ('nec_idade', models.IntegerField(default=0)),
                ('nec_logradouro', models.CharField(max_length=100)),
                ('nec_cpf', models.CharField(max_length=14)),
                ('nec_cid_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.cidade')),
                ('nec_gen_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.genero')),
                ('nec_pro_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.profissao')),
                ('nec_sit_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.situacao')),
            ],
            options={
                'verbose_name': 'Necessitado',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='cid_est_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.estado'),
        ),
        migrations.CreateModel(
            name='TEL_DAS_ONGS',
            fields=[
                ('ton_telefone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ton_ong_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.ong')),
            ],
            options={
                'verbose_name': 'Telefone da ONG',
                'verbose_name_plural': 'Telefone das ONGs',
                'unique_together': {('ton_telefone', 'ton_ong_id')},
            },
        ),
        migrations.CreateModel(
            name='EMAIL_DAS_ONGS',
            fields=[
                ('emo_email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('emo_ong_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.ong')),
            ],
            options={
                'verbose_name': 'E-mail da ONG',
                'verbose_name_plural': 'E-mail das ONGs',
                'unique_together': {('emo_email', 'emo_ong_id')},
            },
        ),
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_nec_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.necessitado')),
                ('att_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'unique_together': {('att_id', 'att_usu_id', 'att_nec_id')},
            },
        ),
    ]
