# Generated by Django 4.1 on 2022-11-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Localidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_generos', models.CharField(max_length=20, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_profissao', models.CharField(max_length=100, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('sit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sit_situacao', models.CharField(max_length=100, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Necessitado',
            fields=[
                ('nec_id', models.AutoField(primary_key=True, serialize=False)),
                ('nec_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nec_idade', models.IntegerField(default=0, verbose_name='Idade')),
                ('nec_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('nec_cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nec_cid_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.cidade', verbose_name='Cidade')),
                ('nec_gen_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.genero', verbose_name='Gênero')),
                ('nec_pro_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.profissao', verbose_name='Profissão')),
                ('nec_sit_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.situacao', verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Necessitado',
            },
        ),
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('att_nec_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('att_nec_idade', models.IntegerField(default=0, verbose_name='Idade')),
                ('att_nec_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('att_nec_cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('att_nec_cid_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.cidade', verbose_name='Cidade')),
                ('att_nec_gen_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.genero', verbose_name='Gênero')),
                ('att_nec_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='necessitado', to='Aplicativo.necessitado', verbose_name='Necessitado')),
                ('att_nec_pro_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.profissao', verbose_name='Profissão')),
                ('att_nec_sit_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.situacao', verbose_name='Situação')),
                ('att_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'unique_together': {('att_id', 'att_usu_id', 'att_nec_id')},
            },
        ),
    ]
