# Generated by Django 4.1.2 on 2022-10-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localidade', '0001_initial'),
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='att_nec_cid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_cid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_cid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.cidade', verbose_name='Cidade da ONG'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
