# Generated by Django 4.1 on 2022-11-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissao',
            options={'ordering': ['pro_profissao'], 'verbose_name': 'Profissão', 'verbose_name_plural': 'Profissões'},
        ),
    ]
