# Generated by Django 4.1 on 2022-10-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='est_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Estado'),
        ),
    ]
