# Generated by Django 4.1 on 2022-09-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero'},
        ),
        migrations.AlterModelOptions(
            name='necessitado',
            options={'verbose_name': 'Necessitado'},
        ),
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name': 'Profissão', 'verbose_name_plural': 'Profissões'},
        ),
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações'},
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cid_id', models.AutoField(primary_key=True, serialize=False)),
                ('cid_cidade', models.CharField(max_length=50)),
                ('cid_est_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.estado')),
            ],
        ),
    ]
