# Generated by Django 4.1.2 on 2022-10-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_alter_atualizacao_att_nec_cid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='ong_cid_id',
        ),
        migrations.AlterUniqueTogether(
            name='tel_das_ongs',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tel_das_ongs',
            name='ton_ong_id',
        ),
        migrations.DeleteModel(
            name='EMAIL_DAS_ONGS',
        ),
        migrations.DeleteModel(
            name='ONG',
        ),
        migrations.DeleteModel(
            name='TEL_DAS_ONGS',
        ),
    ]
