# Generated by Django 4.1 on 2022-09-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_estado_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessitado',
            name='nec_cid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.cidade'),
        ),
    ]
