# Generated by Django 4.1 on 2022-10-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_alter_estado_est_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='cid_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Estado'),
        ),
    ]
