# Generated by Django 4.1 on 2022-10-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_alter_cidade_cid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='cid_est_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='cid_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
