# Generated by Django 4.1 on 2022-09-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_necessitado_nec_cid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tel_dos_usu',
            fields=[
                ('tel_telefone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tel_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.usuario')),
            ],
            options={
                'unique_together': {('tel_telefone', 'tel_usu_id')},
            },
        ),
    ]
