# Generated by Django 4.1 on 2022-11-02 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_remove_ong_ong_cid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='att_nec_cpf',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(14)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_cpf',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(14)], verbose_name='CPF'),
        ),
    ]
