# Generated by Django 4.1 on 2022-10-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Aplicativo', '0004_alter_cidade_cid_est_id_alter_cidade_cid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='att_nec_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.necessitado', verbose_name='Necessitado'),
        ),
        migrations.AlterField(
            model_name='atualizacao',
            name='att_usu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='cid_cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='email_das_ongs',
            name='emo_ong_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.ong', verbose_name='ONG'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='est_estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='est_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='gen_generos',
            field=models.CharField(max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_cid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_gen_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_logradouro',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_pro_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.profissao', verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_sit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.situacao', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_cid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.cidade', verbose_name='Cidade da ONG'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_logradouro',
            field=models.CharField(max_length=50, verbose_name='Logradouro da ONG'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_nome',
            field=models.CharField(max_length=100, verbose_name='Nome da ONG'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_site',
            field=models.CharField(max_length=70, verbose_name='Site da ONG'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='pro_profissao',
            field=models.CharField(max_length=100, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='sit_situacao',
            field=models.CharField(max_length=100, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tel_das_ongs',
            name='ton_ong_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.ong', verbose_name='ONG'),
        ),
    ]
