# Generated by Django 4.1 on 2022-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_alter_atualizacao_att_nec_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='att_nec_cpf',
            field=models.CharField(max_length=11, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='necessitado',
            name='nec_cpf',
            field=models.CharField(max_length=11, verbose_name='Nome'),
        ),
    ]
