# Generated by Django 4.1 on 2022-09-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_usuario_tel_dos_usu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tel_dos_usu',
            options={'verbose_name': 'Telefone de Usuário', 'verbose_name_plural': 'Telefone dos Usuários'},
        ),
        migrations.CreateModel(
            name='EMAIL_DOS_USU',
            fields=[
                ('ema_email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ema_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.usuario')),
            ],
            options={
                'verbose_name': 'E-mail de Usuário',
                'verbose_name_plural': 'E-mail dos Usuários',
                'unique_together': {('ema_email', 'ema_usu_id')},
            },
        ),
    ]
