# Generated by Django 4.1 on 2022-09-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_alter_tel_dos_usu_options_email_dos_usu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_nec_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.necessitado')),
                ('att_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.usuario')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'unique_together': {('att_id', 'att_usu_id', 'att_nec_id')},
            },
        ),
    ]
