# Generated by Django 4.1 on 2022-09-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('ong_id', models.AutoField(primary_key=True, serialize=False)),
                ('ong_nome', models.CharField(max_length=100)),
                ('ong_site', models.CharField(max_length=70)),
                ('ong_logradouro', models.CharField(max_length=50)),
                ('ong_cid_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.cidade')),
            ],
        ),
    ]
