# Generated by Django 4.1 on 2022-10-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(max_length=50, unique=True, verbose_name='Usuário')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='TEL_DOS_USU',
            fields=[
                ('tel_telefone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tel_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
            options={
                'verbose_name': 'Telefone de Usuário',
                'verbose_name_plural': 'Telefone dos Usuários',
                'unique_together': {('tel_telefone', 'tel_usu_id')},
            },
        ),
        migrations.CreateModel(
            name='EMAIL_DOS_USU',
            fields=[
                ('ema_email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ema_usu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
            options={
                'verbose_name': 'E-mail de Usuário',
                'verbose_name_plural': 'E-mail dos Usuários',
                'unique_together': {('ema_email', 'ema_usu_id')},
            },
        ),
    ]
