# Generated by Django 4.1 on 2022-11-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_dos_usu',
            name='ema_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tel_dos_usu',
            name='tel_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email_dos_usu',
            name='ema_email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='email_dos_usu',
            name='ema_usu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='tel_dos_usu',
            name='tel_telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
