# Generated by Django 4.1.2 on 2022-10-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cid_id', models.AutoField(primary_key=True, serialize=False)),
                ('cid_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cid_est_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.estado', verbose_name='Estado')),
            ],
        ),
    ]
