# Generated by Django 4.1 on 2022-11-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Localidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('ong_id', models.AutoField(primary_key=True, serialize=False)),
                ('ong_nome', models.CharField(max_length=100, verbose_name='Nome da ONG')),
                ('ong_site', models.CharField(max_length=70, verbose_name='Site da ONG')),
                ('ong_logradouro', models.CharField(max_length=50, verbose_name='Logradouro da ONG')),
                ('ong_cid_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localidade.cidade', verbose_name='Cidade da ONG')),
            ],
            options={
                'verbose_name': 'ONG',
            },
        ),
        migrations.CreateModel(
            name='TEL_DAS_ONGS',
            fields=[
                ('ton_id', models.AutoField(primary_key=True, serialize=False)),
                ('ton_telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('ton_ong_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ONG.ong', verbose_name='ONG')),
            ],
            options={
                'verbose_name': 'Telefone da ONG',
                'verbose_name_plural': 'Telefone das ONGs',
                'unique_together': {('ton_telefone', 'ton_ong_id')},
            },
        ),
        migrations.CreateModel(
            name='EMAIL_DAS_ONGS',
            fields=[
                ('emo_id', models.AutoField(primary_key=True, serialize=False)),
                ('emo_email', models.CharField(max_length=40, verbose_name='Email')),
                ('emo_ong_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ONG.ong', verbose_name='ONG')),
            ],
            options={
                'verbose_name': 'E-mail da ONG',
                'verbose_name_plural': 'E-mail das ONGs',
                'unique_together': {('emo_email', 'emo_ong_id')},
            },
        ),
    ]
